Q1: Questions on Basic NumPy Array
(a)	Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
(b)	Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods 
(c)	Compare the following numpy arrays: 
arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]]) 
 
(d)	Find the most frequent value and their indice(s) in the following arrays: 
i.	x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii.	y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
(e)	For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
i.	Sum of all elements 
ii.	Sum of all elements row-wise  
iii.	Sum of all elements column-wise 
(f)	For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
i.	Sum of diagonal elements 
ii.	Eigen values of matrix 
iii.	Eigen vectors of matrix iv. Inverse of matrix 
	v. 	Determinant of matrix 
(g)	Multiply the following matrices and also find covariance between matrices using NumPy: i. p = [[1, 2], [2, 3]] q = [[4, 5], [6, 7]] 
ii. 	p = [[1, 2], [2, 3], [4, 5]] q = [[4, 5, 1], [6, 7, 2]] 
(h)	For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), find inner, outer and cartesian product? 


In [5]:

import numpy as np
from numpy import linalg as LA
from collections import Counter
from itertools import product


arr = np.array([1, 2, 3, 6, 4, 5])
print("Q1 (a) - Reversed Array:", arr[::-1])

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Q1 (b) - Flatten (flatten):", array1.flatten())
print("Q1 (b) - Flatten (ravel):", array1.ravel())


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Q1 (c) - Arrays are equal:", np.array_equal(arr1, arr2))


x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])


val_x = Counter(x).most_common(1)[0][0]
indices_x = np.where(x == val_x)[0]
print("Q1 (d.i) - Most frequent in x:", val_x, "Indices:", indices_x)

val_y = Counter(y).most_common(1)[0][0]
indices_y = np.where(y == val_y)[0]
print("Q1 (d.ii) - Most frequent in y:", val_y, "Indices:", indices_y)


gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Q1 (e.i) - Total sum:", gfg.sum())
print("Q1 (e.ii) - Row-wise sum:", gfg.sum(axis=1))
print("Q1 (e.iii) - Column-wise sum:", gfg.sum(axis=0))

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Q1 (f.i) - Diagonal sum:", np.trace(n_array))
eig_vals, eig_vecs = LA.eig(n_array)
print("Q1 (f.ii) - Eigenvalues:", eig_vals)
print("Q1 (f.iii) - Eigenvectors:\n", eig_vecs)
print("Q1 (f.iv) - Inverse:\n", LA.inv(n_array))
print("Q1 (f.v) - Determinant:", LA.det(n_array))


p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("Q1 (g.i) - Matrix Product 1:\n", np.dot(p1, q1))

p1_flat = p1.flatten()
q1_flat = q1.flatten()
combined1 = np.stack((p1_flat, q1_flat), axis=0)
print("Q1 (g.i) - Covariance 1:\n", np.cov(combined1))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("Q1 (g.ii) - Matrix Product 2:\n", np.dot(p2, q2))

p2_flat = p2.flatten()[:6]
q2_flat = q2.flatten()[:6]
combined2 = np.stack((p2_flat, q2_flat), axis=0)
print("Q1 (g.ii) - Covariance 2:\n", np.cov(combined2))


x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Q1 (h) - Inner Product:\n", np.inner(x, y))
print("Q1 (h) - Outer Product:\n", np.outer(x.flatten(), y.flatten()))

cartesian = list(product(x.flatten(), y.flatten()))
print("Q1 (h) - Cartesian Product:\n", cartesian)



Q1 (a) - Reversed Array: [5 4 6 3 2 1]
Q1 (b) - Flatten (flatten): [1 2 3 2 4 5 1 2 3]
Q1 (b) - Flatten (ravel): [1 2 3 2 4 5 1 2 3]
Q1 (c) - Arrays are equal: True
Q1 (d.i) - Most frequent in x: 1 Indices: [0 5 7 8 9]
Q1 (d.ii) - Most frequent in y: 1 Indices: [0 1 2]
Q1 (e.i) - Total sum: 45
Q1 (e.ii) - Row-wise sum: [[14]
 [16]
 [15]]
Q1 (e.iii) - Column-wise sum: [[20  9 16]]
Q1 (f.i) - Diagonal sum: 176
Q1 (f.ii) - Eigenvalues: [28.097044   49.73460452 98.16835147]
Q1 (f.iii) - Eigenvectors:
 [[-0.34637121  0.15017693  0.4574917 ]
 [ 0.72784061  0.4852124   0.28447814]
 [-0.59184038 -0.8614034   0.84248058]]
Q1 (f.iv) - Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Q1 (f.v) - Determinant: 137180.0000000001
Q1 (g.i) - Matrix Product 1:
 [[16 19]
 [26 31]]
Q1 (g.i) - Covariance 1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Q1 (g.ii) - Matrix Product 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Q1 

Q2: Based on NumPy Mathematics and Statistics 
(a)	For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
i.	Find element-wise absolute value 
ii.	Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row. iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row 
(b)	For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values 
 


In [2]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Absolute:\n", np.abs(array))

flat = array.flatten()
print("Percentiles (Flat):", np.percentile(flat, [25, 50, 75]))
print("Percentiles (Col):", np.percentile(array, [25, 50, 75], axis=0))
print("Percentiles (Row):", np.percentile(array, [25, 50, 75], axis=1))

print("Mean (Flat):", flat.mean())
print("Median (Flat):", np.median(flat))
print("Std Dev (Flat):", flat.std())
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Round:", np.round(a))


Absolute:
 [[1 2 3]
 [4 5 6]]
Percentiles (Flat): [-3.5 -0.5  2.5]
Percentiles (Col): [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (Row): [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (Flat): -0.5
Median (Flat): -0.5
Std Dev (Flat): 3.8622100754188224
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting 
(a)	For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
i.	Sorted array 
ii.	Indices of sorted array 
iii.	4 smallest elements 
iv.	5 largest elements 
(b)	For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
i.	Integer elements only 
ii.	Float elements only 


In [3]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print("Indices:", np.argsort(array))
print("4 Smallest:", np.sort(array)[:4])
print("5 Largest:", np.sort(array)[-5:])
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print("Integers:", integers)
print("Floats:", floats)


Sorted: [ 10  16  16  52  54  62 453]
Indices: [0 3 4 1 5 2 6]
4 Smallest: [10 16 16 52]
5 Largest: [ 16  52  54  62 453]
Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]


Q4:  
(a)	Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images) 
(b)	Load the saved file into jupyter notebook? 


In [4]:
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
        print("Grayscale image saved.")
    else:
        for i in range(arr.shape[2]):
            np.savetxt(f"rgb_channel_{i}.txt", arr[:, :, i], fmt='%d')
        print("RGB image saved.")
loaded = np.loadtxt("grayscale_image.txt", dtype=int)
print("Loaded grayscale image:\n", loaded)


<class 'FileNotFoundError'>: grayscale_image.txt not found.